def listnumber(stocklist):
    lookinglist = {
        "stock":1,
        "Low":2,
        "S1":3,
        "Mode":4,
        "S2":5,
        "Mode":6,
        "S3":7,
        "Mode":8,
        "R1":9,
        "Mode":10,
        "R2":11,
        "Mode":12,
        "R3":13,
        "Mode":14,
        "R​4":15,
        "Mode":16,
        "R5":17,
        "Mode":18,
        "LastPrice":19,
        "BreakS1":20,
        "BreakS2":21,
        "BreakS3":22,
        "BreakR1":23,
        "BreakR2":24,
        "BreakR3":25,
        "BreakR4":26,
        "BreakR5":27,
        "Entry":28,
        "Reward":29,
        "Risk":30,
        "RR":31,
        "Entry":32,
        "Reward":33,
        "Risk":34,
        "RR":35,
        }
    stocklistnumber = lookinglist[stocklist]
    return stocklistnumber