def stocknumber(stocknameUP):
    stockdicts = {
        "AAV":3,
        "ADVANC":4,
        "AMATA":5,
        "AOT":6,
        "AP":7,
        "BANPU":8,
        "BBL":9,
        "BCH":10,
        "BCP":11,
        "BCPG":12,
        "BDMS":13,
        "BEAUTY":14,
        "BEM":15,
        "BGRIM":16,
        "BH":17,
        "BJC":18,
        "BLA":19,
        "BLAND":20,
        "BPP":21,
        "BTS":22,
        "CBG":23,
        "CENTEL":24,
        "CHG":25,
        "CK":26,
        "CKP":27,
        "COM7":28,
        "CPALL":29,
        "CPF":30,
        "CPN":31,
        "DELTA":32,
        "DTAC":33,
        "EA":34,
        "EGCO":35,
        "EPG":36,
        "ERW":37,
        "ESSO":38,
        "GFPT":39,
        "GGC":40,
        "GLOBAL":41,
        "GLOW":42,
        "GPSC":43,
        "GUNKUL":44,
        "HANA":45,
        "HMPRO":46,
        "INTUCH":47,
        "IRPC":48,
        "ITD":49,
        "IVL":50,
        "KBANK":51,
        "KCE":52,
        "KKP":53,
        "KTB":54,
        "KTC":55,
        "LH":56,
        "LPN":57,
        "MAJOR":58,
        "MEGA":59,
        "MINT":60,
        "MTC":61,
        "ORI":62,
        "PRM":63,
        "PSH":64,
        "PSL":65,
        "PTG":66,
        "PTT":67,
        "PTTEP":68,
        "PTTGC":69,
        "QH":70,
        "RATCH":71,
        "ROBINS":72,
        "RS":73,
        "SAWAD":74,
        "SCB":75,
        "SCC":76,
        "SGP":77,
        "SIRI":78,
        "SPALI":79,
        "SPRC":80,
        "STA":81,
        "STEC":82,
        "SUPER":83,
        "TASCO":84,
        "TCAP":85,
        "THAI":86,
        "THANI":87,
        "TISCO":88,
        "TKN":89,
        "TMB":90,
        "TOA":91,
        "TOP":92,
        "TPIPL":93,
        "TPIPP":94,
        "TRUE":95,
        "TTW":96,
        "TU":97,
        "TVO":98,
        "UV":99,
        "WHA":100,
        "WHAUP":101,
        "WORK":102,
    }
    stocknumber = stockdicts[stocknameUP]
    return stocknumber

# stockdicts = {
#     "AAV":3,
#     "ADVANC":4,
#     "AMATA":5,
#     "AOT":6,
#     "AP":7,
#     "BANPU":8,
#     "BBL":9,
#     "BCH":10,
#     "BCP":11,
#     "BCPG":12,
#     "BDMS":13,
#     "BEAUTY":14,
#     "BEM":15,
#     "BGRIM":16,
#     "BH":17,
#     "BJC":18,
#     "BLA":19,
#     "BLAND":20,
#     "BPP":21,
#     "BTS":22,
#     "CBG":23,
#     "CENTEL":24,
#     "CHG":25,
#     "CK":26,
#     "CKP":27,
#     "COM7":28,
#     "CPALL":29,
#     "CPF":30,
#     "CPN":31,
#     "DELTA":32,
#     "DTAC":33,
#     "EA":34,
#     "EGCO":35,
#     "EPG":36,
#     "ERW":37,
#     "ESSO":38,
#     "GFPT":39,
#     "GGC":40,
#     "GLOBAL":41,
#     "GLOW":42,
#     "GPSC":43,
#     "GUNKUL":44,
#     "HANA":45,
#     "HMPRO":46,
#     "INTUCH":47,
#     "IRPC":48,
#     "ITD":49,
#     "IVL":50,
#     "KBANK":51,
#     "KCE":52,
#     "KKP":53,
#     "KTB":54,
#     "KTC":55,
#     "LH":56,
#     "LPN":57,
#     "MAJOR":58,
#     "MEGA":59,
#     "MINT":60,
#     "MTC":61,
#     "ORI":62,
#     "PRM":63,
#     "PSH":64,
#     "PSL":65,
#     "PTG":66,
#     "PTT":67,
#     "PTTEP":68,
#     "PTTGC":69,
#     "QH":70,
#     "RATCH":71,
#     "ROBINS":72,
#     "RS":73,
#     "SAWAD":74,
#     "SCB":75,
#     "SCC":76,
#     "SGP":77,
#     "SIRI":78,
#     "SPALI":79,
#     "SPRC":80,
#     "STA":81,
#     "STEC":82,
#     "SUPER":83,
#     "TASCO":84,
#     "TCAP":85,
#     "THAI":86,
#     "THANI":87,
#     "TISCO":88,
#     "TKN":89,
#     "TMB":90,
#     "TOA":91,
#     "TOP":92,
#     "TPIPL":93,
#     "TPIPP":94,
#     "TRUE":95,
#     "TTW":96,
#     "TU":97,
#     "TVO":98,
#     "UV":99,
#     "WHA":100,
#     "WHAUP":101,
#     "WORK":102,
# }

# for stockdict in stockdicts.values():
#     print(stockdict)
# stocknameUP = "DTAC"
# for stockdict in stockdicts:
#     print(stockdict)

# stocknumber = stockdicts[stocknameUP]
# print(stocknumber)

# getstocknumber = stocknumber(stocknameUP)
# print(getstocknumber)
# print(type(getstocknumber))